// Generated by CoffeeScript 1.8.0
(function() {
  var getDisplayValue, parseCalculation, setDisplayValue;

  getDisplayValue = function() {
    return parseInt($('th').text());
  };

  setDisplayValue = function(value) {
    return $('th').text(value);
  };

  parseCalculation = function(num1, num2, operator) {
    switch (operator) {
      case '+':
        return num1 + num2;
      case '-':
        return num1 - num2;
      case 'X':
        return num1 * num2;
      case '/':
        return num1 / num2;
      case '':
        return 0;
    }
  };

  $(document).ready(function() {
    var displayValue, num1, num2, operator;
    displayValue = "";
    num1 = 0;
    num2 = 0;
    operator = "";
    $('.num').click(function() {
      displayValue += $(this).text();
      return setDisplayValue(displayValue);
    });
    $('.operation').click(function() {
      num1 = parseInt(displayValue);
      operator = $(this).text();
      displayValue = "";
      return setDisplayValue(displayValue);
    });
    $('#equals').click(function() {
      num2 = parseInt(displayValue);
      displayValue = parseCalculation(num1, num2, operator);
      setDisplayValue(displayValue);
      num1 = displayValue;
      return operator = "";
    });
    return $('#clear').click(function() {
      displayValue = "";
      num1 = 0;
      num2 = 0;
      operator = '';
      return setDisplayValue(displayValue);
    });
  });

}).call(this);
