// Generated by CoffeeScript 1.8.0
(function() {
  var incrementCircle, incrementCount, randomColor, setOpacityOf;

  incrementCircle = function() {
    var newSize;
    newSize = circle.height() + 2;
    circle.height(newSize);
    circle.width(newSize);
    circle.css('visibility', 'visible');
    circle.css('border-radius', newSize);
    circle.css('margin-top', newSize / -2);
    circle.css('margin-left', newSize / -2);
    circle.css('background-color', randomColor());
    setOpacityOf(circle);
    return incrementCount();
  };

  setOpacityOf = function(circle) {
    if (circle.css('opacity') === '1') {
      return circle.css('opacity', '0.5');
    } else {
      return circle.css('opacity', '1');
    }
  };

  randomColor = function() {
    return "#" + (Math.floor(Math.random() * 16777215).toString(16));
  };

  incrementCount = function() {
    var number;
    number = $("span").text();
    return $("span").text((+number) + 1);
  };

  $(document).ready(function() {
    document.getElementById('audiotag1').play();
    window.circle = $("div");
    incrementCircle;
    return setInterval(incrementCircle, 1);
  });

}).call(this);
