// Generated by CoffeeScript 1.8.0
(function() {
  var displayWeather, shiftBackgroundColorToTemperature;

  $(document).ready(function() {
    $('input').focus();
    return $('form').on('submit', function(event) {
      var query, script;
      event.preventDefault();
      query = $('input').val();
      script = document.createElement("script");
      script.src = "http://api.worldweatheronline.com/free/v1/weather.ashx?q=" + query + "&format=json&callback=processWeather&key=j8xvysb7t9jp2dvw7pwcbgs3";
      return document.body.appendChild(script);
    });
  });

  window.processWeather = function(weather) {
    var currentConditions, forecast, temperature;
    if (weather.data.error) {
      return $("#weather").html("<h1>An error has occurred</h1>");
    } else {
      currentConditions = weather.data.current_condition[0];
      temperature = currentConditions.temp_F;
      forecast = currentConditions.weatherDesc[0].value;
      return displayWeather(temperature, forecast);
    }
  };

  displayWeather = function(temperature, forecast) {
    var template;
    template = _.template("<div> " + "<h1><%= temperature %> degrees</h1>" + "<h1><%= forecast %></h1>" + "</div>");
    $('#weather').html(template({
      temperature: temperature,
      forecast: forecast
    }));
    return shiftBackgroundColorToTemperature(temperature);
  };

  shiftBackgroundColorToTemperature = function(temperature) {
    var climates, color;
    climates = {
      supercold: "rgb(20, 105, 234)",
      cold: "rgb(112, 142, 187)",
      meh: "rgb(217, 222, 229)",
      warm: "rgb(247, 236, 129)",
      hot: "rgb(237, 176, 176)",
      superhot: "rgb(242, 1, 1)",
      unknown: "rgb(0, 0, 0"
    };
    switch (true) {
      case temperature < 10:
        color = "supercold";
        break;
      case temperature < 30:
        color = "cold";
        break;
      case temperature < 50:
        color = "meh";
        break;
      case temperature < 70:
        color = "warm";
        break;
      case temperature < 90:
        color = "hot";
        break;
      case temperature < 110:
        color = "superhot";
        break;
      default:
        color = "unknown";
    }
    return $('body').animate({
      backgroundColor: climates[color]
    }, 'slow');
  };

}).call(this);
