// Generated by CoffeeScript 1.8.0
(function() {
  var getColor;

  getColor = function(position) {
    return "#" + (Math.floor((position / 1500) * 16777215).toString(16));
  };

  $(document).ready(function() {
    return $(document).mousemove(function(e) {
      var element;
      element = $('<div style=\"height:' + ("" + (e.pageY / 5) + "px;\"") + '></div>');
      element.css("background-color", getColor(e.pageX));
      return $("main").append(element);
    });
  });

}).call(this);
