// Generated by CoffeeScript 1.8.0
(function() {
  var endpointURL, movieTemplate, request;

  endpointURL = function(requestType) {
    return "http://api.rottentomatoes.com/api/public/v1.0/lists/movies/" + requestType + ".json?apikey=pgdtp25vavmj5fdbu2ynamxc";
  };

  this.displayMovies = function(response) {
    $("#movies").empty();
    return $.each(response.movies, function(i, movie) {
      return $("#movies").append(movieTemplate(movie.links.alternate, movie.posters.detailed));
    });
  };

  movieTemplate = function(a, src) {
    return "<a href='" + a + "'><img class='movie' src='" + src + "'/></a>";
  };

  request = function(requestType) {
    return {
      url: endpointURL(requestType),
      jsonpCallback: "displayMovies",
      dataType: "jsonp"
    };
  };

  $(document).ready(function() {
    $('#opening').click(function() {
      return $.ajax(request("opening"));
    });
    $('#now').click(function() {
      return $.ajax(request("in_theaters"));
    });
    return $('#coming').click(function() {
      return $.ajax(request("upcoming"));
    });
  });

}).call(this);
